### ISSUE TITLE
fpm image, use entrypoint

### ISSUE THREAD

**Issue by adrianlzt** [Tenzer/dockerfiles#2]
And to be more standard, maybe CMD could be changed to --help and set an Entrypoint to fpm.

With that, if the containers is run without params, it will show fpm help.

If some params is passed it will be used as a param to the fpm bin.

**Comment by Tenzer** [comment]
I guess you're right. I've just never really liked `ENTRYPOINT` much as it tends to just cause more confusion and is annoying to overrule compared to `CMD`.

But citing https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#entrypoint:

> The best use for `ENTRYPOINT` is to set the image’s main command, allowing that image to be run as though it was that command (and then use `CMD` as the default flags).

Since the fpm image only is intended for running fpm then it makes sense in this case. I'll change it.

**Comment by jigfox** [comment]
sadly this broke a lot of builds in our CI, because we use gitlab-ci with this docker container, but it won't work now, because we need to run our commands within this container. Could you please use other tags than latest for versioning and may also for two versions one with entrypoint and one without?

**Comment by Tenzer** [comment]
@jigfox Honestly I don't know anything about how much this Docker image is used. For all I know it could just be me. There's no good way for me to communicate breaking changes like this and the Docker community doesn't have any good way of handling changes such as this.

I think my recommendation would be for you to use `--entrypoint <command>` in order to overrule `fpm` being run by default, if you have a need for that. I'm not too keen on having different versions of the image, since the way it now works (with `ENTRYPOINT` set) probably matches people's expectations better from other Docker images which only contain one command.

Is that a useable suggestion for you?

**Comment by jigfox** [comment]
no because currently we are not able to use this (https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1421), our solution for now is, we create our own image. But it still would be nice to not just use latest but some kind of versioning, than everyone using this image could use the version required and is not forced to use `:latest`

**Comment by Tenzer** [comment]
I have made a separate branch on this repository now called "no-entrypoint" and set up Docker Hub to build a separate tag, `:no-entrypoint` which does not set `ENTRYPOINT` in the Dockerfile. The build is running now and should be available shortly. Log: https://hub.docker.com/r/tenzer/fpm/builds/bbwqyarrzaxhjnbmwrkgfte/.

**Comment by jigfox** [comment]
thanks very much, that should work

**Comment by Tenzer** [comment]
There you go:
```
[jeppe@reventon ~]$ docker inspect tenzer/fpm:latest | jq '.[0].ContainerConfig | {Cmd: .Cmd, Entrypoint: .Entrypoint}'
{
  "Cmd": [
    "/bin/sh",
    "-c",
    "#(nop) ",
    "CMD [\"--help\"]"
  ],
  "Entrypoint": [
    "fpm"
  ]
}
[jeppe@reventon ~]$ docker inspect tenzer/fpm:no-entrypoint | jq '.[0].ContainerConfig | {Cmd: .Cmd, Entrypoint: .Entrypoint}'
{
  "Cmd": [
    "/bin/sh",
    "-c",
    "#(nop) ",
    "CMD [\"fpm\"]"
  ],
  "Entrypoint": null
}
```

**Comment by jigfox** [comment]
thanks, this is appreciated
